### PR TITLE
feat: Allow breaking changes

### PR DESCRIPTION
**Pull request by ProMastersss**
- The code is divided into modules;
- Added support for the allowBreakingChanges parameter.

### CODE REVIEW

**Comment by ProMastersss** [comment]
What should I do about it? ERROR: 1:25  no-implicit-dependencies  Module 'vscode' is not listed as dependency in package.json

**Comment by KnisterPeter** [comment]
@ProMastersss wow, thats awesome. Unfortunately this is more a complete rewrite.
If you want to have these I would prefer to do this in separate commits/prs. I have a hard time reviewing all your changes if everything is changed.

**Comment by ProMastersss** [comment]
In the first commit, I did not change anything, only spread it in files for easy understanding of the code. All the changes (there are few of them) were made in the second commit

**Comment by KnisterPeter** [comment]
@ProMastersss Yes, but spliting everything into multiple files is a change on every line of the project. That's what makes it hard to review. It would be better to do the shift in either a series of changes in separate PRs or only do the change you need (allow breaking changes).

**Comment by ProMastersss** [comment]
Added a new branch. It contains only the required changes #406

**Comment by KnisterPeter** [comment]
Can we close this then?

**Comment by ProMastersss** [comment]
Yes

**Pull request closed without merging**
