### PR TITLE
feat: add git top level option

### LINKED ISSUE #419: Git Project root for config
Is it possible to have the extension look at the git project root for configuration files?
Something like calling `git rev-parse --show-toplevel` during the extension startup?

### PR DESCRIPTION
**Pull request by solaris765**
Adds optional git root config locations. New option defaults to false.

closes #419

### CODE REVIEW

**Comment by solaris765** [comment]
I ended up adding a new function for determining the config lookup location called `findLookupPath`.
The logic follows the same pattern as the original for workspace lookups
``` js
if (!vscode.workspace.workspaceFolders) {
    return undefined;
}
```
to
``` js
const lookupPath = await findLookupPath();
if (!lookupPath) {
    return undefined;
}
```

I also didn't tell if any tests where included for the other vscode settings so I didn't write any in to avoid adding complexity to existing tests. 
But the locally tested and expected behavior is for the git command to log any failures to the extension log and fallback to the original workspace logic.

**Comment by KnisterPeter** [comment]
@solaris765 Wow, nice. :rocket: 
Can you rebase to resolve the conflicts?

**Comment by solaris765** [comment]
All set :+1:

**Comment by KnisterPeter** [comment]
@shipjs prepare

**Comment by KnisterPeter** [comment]
Will be released in [v0.12.0](https://github.com/KnisterPeter/vscode-commitizen/pull/426)

**Pull request merged**
