### PR TITLE
feat: consider allowBreakingChanges

### PR DESCRIPTION
**Pull request by ProMastersss**
Added support for the allowBreakingChanges parameter.

### CODE REVIEW

**Comment by KnisterPeter** [comment]
Very nice. Thanks for your contribution :tada:

**Comment by KnisterPeter** [comment]
Unfortunatelly the release v0.10.0 failed and now we have v0.10.1. But the changelog is missing.
I hope you don't mind

**Comment by SkeLLLa** [comment]
@ProMastersss could you please explain a bit more about this PR, since it's introduced a new issue. How and where that `allowBreakingChanges` supported?

**Comment by ProMastersss** [comment]
@SkeLLLa This parameter is now taken into account when committing. For the types specified in it, you will be asked to fill in Breaking changes. The parmeter is specified in the configuration file .cz-config.js. For exact changes to the code, you can look in PR. Parameter description https://github.com/leoforfree/cz-customizable

**Comment by SkeLLLa** [comment]
Thanks. Maybe it worth to pass it to plugin config as well, so it will be configurable from extension settings.

**Comment by ProMastersss** [comment]
This parameter is optional. But now because of a bug it turned out to be mandatory(

**Pull request merged**
