### PR TITLE
fix(bug): add body in section message commit

### PR DESCRIPTION
**Pull request by ProMastersss**
The message body in commit message was not taken into account

### CODE REVIEW

**Comment by ProMastersss** [comment]
Merged a branch, but it didn't make it into the release. When is the next release coming? Message body commit still doesn't work

**Comment by KnisterPeter** [comment]
Oh, that slipped through probably.
@shipjs prepare

**Comment by KnisterPeter** [comment]
@shipjs prepare

**Comment by KnisterPeter** [comment]
The release process fails currently.
I'll inspect and do it later on.

**Comment by KnisterPeter** [comment]
Published as 1.0.2

**Pull request merged**
