### PR TITLE
Allow skipping questions

### LINKED ISSUE #216: Prompt does not skip questions defined in .cz-config.js
First off thanks for the extension, it has become an essential for me!

I have a `.cz-config.js` file with the following fields:

```
module.exports = {
  types: [
    { value: "feat", name: "feat:       A new feature" },
    { value: "fix", name: "fix:        A bug fix" },
    // Some other types
  ],
  messages: {
    type: "Select the type of change that you're committing:",
    scope: "\nDenote the SCOPE of this change (optional):",
    subject: "Write a SHORT, IMPERATIVE tense description of the change:\n",
    body: 'Provide a LONGER description of the change (optional). Use "|" to break new line:\n',
    confirmCommit: "Are you sure you want to proceed with the commit above?"
  },
  skipQuestions: ["footer", "breaking"] // HERE
};
```

I am using cz-customizable as such in `package.json`:

```
"scripts": {
   "commit": "git-cz",
// some other scripts
},
"config": {
    "commitizen": {
      "path": "node_modules/cz-customizable"
    }
  }
```

With this configuration, `git cz` effectively skips the footer and breaking changes prompts, but running conventional commit from the command panel still asks me those questions.

Is skipping questions supposed to work on this extension or is my config wrong?
Thanks!

### PR DESCRIPTION
**Pull request by yassinecc**
Fixes #216

### CODE REVIEW

**Comment by yassinecc** [comment]
@KnisterPeter It looks like the VSCode extension tests fail all PRs since August 1st

**Comment by KnisterPeter** [comment]
@yassinecc I will have a look as soon as possible.

**Comment by KnisterPeter** [comment]
Awesome. I will merge and release later. :rocket:

**Comment by yassinecc** [comment]
Hello @KnisterPeter any news on this?

**Comment by KnisterPeter** [comment]
Hi @yassinecc, I thougt you fixed the test, but I think you removed the fix afterwards.
Right now I have no computer to investigate the isse.

**Comment by yassinecc** [comment]
@KnisterPeter I tried to fix the tests but in the end could not reproduce the issue, I think it happens only on Linux platforms as the CI script works fine on my Mac

**Comment by KnisterPeter** [comment]
I'm back from vacation next week and will take a look.

**Comment by yassinecc** [comment]
@KnisterPeter I found out why tests were failing: the CI build environment got updated to Xenial 16.04 and there was a breaking change in the way to setup GUI testing with xvfb, more info can be found [here](https://benlimmer.com/2019/01/14/travis-ci-xvfb/)

**Comment by KnisterPeter** [comment]
@yassinecc As well I'm splitted the fix for xvfb into a separate PR since multiple PRs are depending on this change/fix.

**Comment by yassinecc** [comment]
@KnisterPeter I have updated the PR with signed commits :)

**Comment by KnisterPeter** [comment]
@yassinecc Published as 0.8.4 :rocket: 
Thanks for you patience with me and many thanks for contributing.

**Pull request merged**
