### PR TITLE
Added emojis for each commit type

### PR DESCRIPTION
**Pull request by ivalsaraj**
I've added emoji for each commit type, also it will convert to emoji code while committing

eg: `git commit -m feat(test): :sparkles: testinggggg`

image

### CODE REVIEW

**Comment by KnisterPeter** [comment]
@ivalsaraj Nice idea. But I would favor this to be configurable (and by default off) since there may be a lot users which do not expect this and want this.
Can you please add an option for this?

**Comment by ivalsaraj** [comment]
@KnisterPeter That's good! Letting users to decide.
 I'm not that good at typescript to be frank.

**Comment by KnisterPeter** [comment]
@ivalsaraj No problem. If there are any problem feel free to ask me.

**Comment by tehshane** [comment]
If I can add a note, too, from a visual perspective, the spacing between the type name and the description is pretty ragged looking. Is it possible to place the emoji to the left of the feature name so it's a little more lined up?
 
eg.
>✨ **feat** A new feature
>🐛 **fix** A bug fix
>📖 **docs** Documentation only changes
>💄 **style** Changes that do not affect the meaning of the code...

... and so on.

It's still not perfectly aligned, but I'd prefer it to the alternative.
Also +1 to what @KnisterPeter proposed: I'd like the option to opt-out of emoji in my config.

**Comment by KnisterPeter** [comment]
Having the emoji left of the type would be against conventional commit syntax, so I would vote against it.
Also emojis should be opt-in instead of opt-out I suppose.

**Comment by tehshane** [comment]
> Having the emoji left of the type would be against conventional commit syntax, so I would vote against it.
> Also emojis should be opt-in instead of opt-out I suppose.

Sorry, I should have clarified (if it makes a difference), I meant in the VSCode UI, not the commit message itself.

**Comment by KnisterPeter** [comment]
@ivalsaraj Is this stale? Should I close this or do you still work on it?

**Comment by KnisterPeter** [comment]
I will close this for now. Feel free to reopen and update.

**Pull request closed without merging**
