### PR TITLE
style: add logo

### LINKED ISSUE #11: Default icon
Hi @KnisterPeter 

You can use this image as icon

`Microsoft.VisualStudio.Services.Icons.Default`

image

Best regards.

### PR DESCRIPTION
**Pull request by sehwol**
Resolving an old request to add the cz logo.

Close #11

### CODE REVIEW

**Comment by sehwol** [comment]
Extra question:

If I want to refactor and add some features/tests (moving/adding a lot of code), what's the best way to do it without messing with any contributor's work?

**Comment by KnisterPeter** [comment]
@sehwol You can just update and refactor as you like. I can also make you contributor if you want to. Then you can merge on your own.

**Comment by KnisterPeter** [comment]
@sehwol Please wait a bit, I'll doing a big refactoring/clean and add prettier. This will change the codestyle but make it easier in the future.

**Comment by KnisterPeter** [comment]
@sehwol Done with the refactoring. Feel free to refactor what you like.

**Pull request merged**
